### ISSUE TITLE
Please show more information when downloading the ledger file.

### ISSUE THREAD

**Issue by miki151** [nano-wallet-company/nano-wallet-desktop#30]
Size of the file, ETA, etc. Please show a warning if there isn't enough disk space!

Also please allow changing the destination directory before downloading. The file is really big and not everyone has that amount of space on their c: or / drive.

Also it seems that the app doesn't continue interrupted download, and it ignores that file, so it stays in the temp dir occupying disk space.

**Comment by Byzantined** [comment]
Agreed - 
I've just downloaded & launched the latest Beta Desktop wallet for OSX.

That initial launch window "Let's get your wallet set up" should explain what is happening :-  
"This Desktop wallet is a full node which will help run the NANO network, as such it will first download the NANO blockchain. The blockchain is currently in excess of 5GB. Pausing the download will restart the process. "

This will help people decide if they....  
1.. Can afford to download 5GB on their data plan. 
2. Have the time right now to do this.  
3. Want the full node - point to Light wallet options.

**Comment by formaldehid** [comment]
Is anybody doing this issue or I can start with it? @devinus @kennedybaird

**Comment by kennedybaird** [comment]
A new release is rolling out in next couple of days I think so maybe wait
till after then, I think a new login flow was on the cards

**Comment by formaldehid** [comment]
Ok I will wait, after that it would be great if someone says what to do to contribute :)

**Comment by Morty-C-137** [comment]
+1
I just lost several hours trying to get the wallet up and running on linux. If the wallet runs out of disk space while unpacking it just stops and the user does not get a notification. After finding out what's happening you have to free disk space and retry (including re-download). Had to do that several times because theres no way to know how much space will be needed.
This should be much more user friendly

**Comment by mrspiderbrain** [comment]
+1 for more install information eg how much data is required, where the data is going eg directory location and progress on download,

**Comment by zevero** [comment]
This is now my third time restarting to Download data. When the screensaver kicks in, or when WiFi disconnects, download just stops, without any error handling.
On restart data download starts from scratch ... please add a resume function!!!
Nano should be a nice experience ... many users will turn away otherwise...

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
