### ISSUE TITLE
macOS 10.12.6 seed import has the correct account address but balance is still 0

### ISSUE THREAD

**Issue by iouwon** [nano-wallet-company/nano-wallet-desktop#65]
I tried to recreate my account wallet on my macOS desktop nano wallet and when i enter the seed it resolves the account address correctly but the balance is still zero

**Comment by kennedybaird** [comment]
Hi, can you hover over the "reception" icon beside the NANO logo and then copy paste the stats in here?

**Comment by iouwon** [comment]
Sorry, no nano logo on mine, but there is a stats page on the Advanced tab.
Attached

**Comment by kennedybaird** [comment]
Can you provide a screenshot?

**Comment by iouwon** [comment]
I attached one in my original email reply and again here. Do i need to
attach it on github?

**Comment by iouwon** [comment]
<img width="612" alt="screen shot 2018-07-26 at 13 38 18" src="https://user-images.githubusercontent.com/12023443/43265415-95d4b908-90e0-11e8-9424-9b6237cd8d71.png">

**Comment by kennedybaird** [comment]
Think you need to come to the page to do it, can't see on either comment

**Comment by kennedybaird** [comment]
Ok, firstly you're not using the wallet that is in this repo.

That is the wallet from https://www.github.com/nanocurrency/raiblocks which is the old developer wallet

Secondly, I think it's because your wallet isn't synchronized which means it doesn't have up to date information.

Try downloading this wallet and see where it gets you http://nanowalletcompany.com

That is the wallet that this repository is for

**Comment by iouwon** [comment]
My bad. I'd previously installed the wallet from nano.org and thought I'd
removed it so just hit the first nano result from my spotlight

Had hit a refresh button a few times so I'm not sure where the sync
function is on that other wallet

Sorry for wasting your time
